# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce70ed3b825cafdd5a9d043794638db20473d0640df37bbd32785a253c624bca6d76c4b7eeb9111088b58a5d63ece2d8e5d94f6523bb1ce6bbb74e211be57009

test:
  secret_key_base: a7088aee8356a92e5d228682b9848e8845f410af39fead2ae1025267d75ed1d0af0da1cf770ae809899b69838f34f11dc658c86482d02dc79ebddf3bb1f1e9ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
